// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vriscv_soc__Syms.h"


void Vriscv_soc___024root__traceInitSub0(Vriscv_soc___024root* vlSelf, VerilatedVcd* tracep) VL_ATTR_COLD;

void Vriscv_soc___024root__traceInitTop(Vriscv_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vriscv_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    {
        Vriscv_soc___024root__traceInitSub0(vlSelf, tracep);
    }
}

void Vriscv_soc___024root__traceInitSub0(Vriscv_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vriscv_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+278,"clock", false,-1);
        tracep->declBit(c+279,"reset", false,-1);
        tracep->declQuad(c+280,"io_difftest_reg_0", false,-1, 63,0);
        tracep->declQuad(c+282,"io_difftest_reg_1", false,-1, 63,0);
        tracep->declQuad(c+284,"io_difftest_reg_2", false,-1, 63,0);
        tracep->declQuad(c+286,"io_difftest_reg_3", false,-1, 63,0);
        tracep->declQuad(c+288,"io_difftest_reg_4", false,-1, 63,0);
        tracep->declQuad(c+290,"io_difftest_reg_5", false,-1, 63,0);
        tracep->declQuad(c+292,"io_difftest_reg_6", false,-1, 63,0);
        tracep->declQuad(c+294,"io_difftest_reg_7", false,-1, 63,0);
        tracep->declQuad(c+296,"io_difftest_reg_8", false,-1, 63,0);
        tracep->declQuad(c+298,"io_difftest_reg_9", false,-1, 63,0);
        tracep->declQuad(c+300,"io_difftest_reg_10", false,-1, 63,0);
        tracep->declQuad(c+302,"io_difftest_reg_11", false,-1, 63,0);
        tracep->declQuad(c+304,"io_difftest_reg_12", false,-1, 63,0);
        tracep->declQuad(c+306,"io_difftest_reg_13", false,-1, 63,0);
        tracep->declQuad(c+308,"io_difftest_reg_14", false,-1, 63,0);
        tracep->declQuad(c+310,"io_difftest_reg_15", false,-1, 63,0);
        tracep->declQuad(c+312,"io_difftest_reg_16", false,-1, 63,0);
        tracep->declQuad(c+314,"io_difftest_reg_17", false,-1, 63,0);
        tracep->declQuad(c+316,"io_difftest_reg_18", false,-1, 63,0);
        tracep->declQuad(c+318,"io_difftest_reg_19", false,-1, 63,0);
        tracep->declQuad(c+320,"io_difftest_reg_20", false,-1, 63,0);
        tracep->declQuad(c+322,"io_difftest_reg_21", false,-1, 63,0);
        tracep->declQuad(c+324,"io_difftest_reg_22", false,-1, 63,0);
        tracep->declQuad(c+326,"io_difftest_reg_23", false,-1, 63,0);
        tracep->declQuad(c+328,"io_difftest_reg_24", false,-1, 63,0);
        tracep->declQuad(c+330,"io_difftest_reg_25", false,-1, 63,0);
        tracep->declQuad(c+332,"io_difftest_reg_26", false,-1, 63,0);
        tracep->declQuad(c+334,"io_difftest_reg_27", false,-1, 63,0);
        tracep->declQuad(c+336,"io_difftest_reg_28", false,-1, 63,0);
        tracep->declQuad(c+338,"io_difftest_reg_29", false,-1, 63,0);
        tracep->declQuad(c+340,"io_difftest_reg_30", false,-1, 63,0);
        tracep->declQuad(c+342,"io_difftest_reg_31", false,-1, 63,0);
        tracep->declQuad(c+344,"io_difftest_pc", false,-1, 63,0);
        tracep->declBus(c+346,"io_difftest_inst", false,-1, 31,0);
        tracep->declBit(c+347,"io_difftest_commit", false,-1);
        tracep->declBit(c+278,"riscv_soc clock", false,-1);
        tracep->declBit(c+279,"riscv_soc reset", false,-1);
        tracep->declQuad(c+280,"riscv_soc io_difftest_reg_0", false,-1, 63,0);
        tracep->declQuad(c+282,"riscv_soc io_difftest_reg_1", false,-1, 63,0);
        tracep->declQuad(c+284,"riscv_soc io_difftest_reg_2", false,-1, 63,0);
        tracep->declQuad(c+286,"riscv_soc io_difftest_reg_3", false,-1, 63,0);
        tracep->declQuad(c+288,"riscv_soc io_difftest_reg_4", false,-1, 63,0);
        tracep->declQuad(c+290,"riscv_soc io_difftest_reg_5", false,-1, 63,0);
        tracep->declQuad(c+292,"riscv_soc io_difftest_reg_6", false,-1, 63,0);
        tracep->declQuad(c+294,"riscv_soc io_difftest_reg_7", false,-1, 63,0);
        tracep->declQuad(c+296,"riscv_soc io_difftest_reg_8", false,-1, 63,0);
        tracep->declQuad(c+298,"riscv_soc io_difftest_reg_9", false,-1, 63,0);
        tracep->declQuad(c+300,"riscv_soc io_difftest_reg_10", false,-1, 63,0);
        tracep->declQuad(c+302,"riscv_soc io_difftest_reg_11", false,-1, 63,0);
        tracep->declQuad(c+304,"riscv_soc io_difftest_reg_12", false,-1, 63,0);
        tracep->declQuad(c+306,"riscv_soc io_difftest_reg_13", false,-1, 63,0);
        tracep->declQuad(c+308,"riscv_soc io_difftest_reg_14", false,-1, 63,0);
        tracep->declQuad(c+310,"riscv_soc io_difftest_reg_15", false,-1, 63,0);
        tracep->declQuad(c+312,"riscv_soc io_difftest_reg_16", false,-1, 63,0);
        tracep->declQuad(c+314,"riscv_soc io_difftest_reg_17", false,-1, 63,0);
        tracep->declQuad(c+316,"riscv_soc io_difftest_reg_18", false,-1, 63,0);
        tracep->declQuad(c+318,"riscv_soc io_difftest_reg_19", false,-1, 63,0);
        tracep->declQuad(c+320,"riscv_soc io_difftest_reg_20", false,-1, 63,0);
        tracep->declQuad(c+322,"riscv_soc io_difftest_reg_21", false,-1, 63,0);
        tracep->declQuad(c+324,"riscv_soc io_difftest_reg_22", false,-1, 63,0);
        tracep->declQuad(c+326,"riscv_soc io_difftest_reg_23", false,-1, 63,0);
        tracep->declQuad(c+328,"riscv_soc io_difftest_reg_24", false,-1, 63,0);
        tracep->declQuad(c+330,"riscv_soc io_difftest_reg_25", false,-1, 63,0);
        tracep->declQuad(c+332,"riscv_soc io_difftest_reg_26", false,-1, 63,0);
        tracep->declQuad(c+334,"riscv_soc io_difftest_reg_27", false,-1, 63,0);
        tracep->declQuad(c+336,"riscv_soc io_difftest_reg_28", false,-1, 63,0);
        tracep->declQuad(c+338,"riscv_soc io_difftest_reg_29", false,-1, 63,0);
        tracep->declQuad(c+340,"riscv_soc io_difftest_reg_30", false,-1, 63,0);
        tracep->declQuad(c+342,"riscv_soc io_difftest_reg_31", false,-1, 63,0);
        tracep->declQuad(c+344,"riscv_soc io_difftest_pc", false,-1, 63,0);
        tracep->declBus(c+346,"riscv_soc io_difftest_inst", false,-1, 31,0);
        tracep->declBit(c+347,"riscv_soc io_difftest_commit", false,-1);
        tracep->declBit(c+278,"riscv_soc core_clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core_reset", false,-1);
        tracep->declQuad(c+1,"riscv_soc core_io_in_rdata", false,-1, 63,0);
        tracep->declQuad(c+3,"riscv_soc core_io_out_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc core_io_out_wdata", false,-1, 63,0);
        tracep->declQuad(c+7,"riscv_soc core_io_out_raddr", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core_io_out_wen", false,-1);
        tracep->declBus(c+10,"riscv_soc core_io_out_wstrb", false,-1, 7,0);
        tracep->declBit(c+11,"riscv_soc core_difftest_commit", false,-1);
        tracep->declQuad(c+12,"riscv_soc core_difftest_pc", false,-1, 63,0);
        tracep->declBus(c+14,"riscv_soc core_difftest_inst", false,-1, 31,0);
        tracep->declQuad(c+348,"riscv_soc core__WIRE_0", false,-1, 63,0);
        tracep->declQuad(c+15,"riscv_soc core__WIRE_1", false,-1, 63,0);
        tracep->declQuad(c+17,"riscv_soc core__WIRE_2", false,-1, 63,0);
        tracep->declQuad(c+19,"riscv_soc core__WIRE_3", false,-1, 63,0);
        tracep->declQuad(c+21,"riscv_soc core__WIRE_4", false,-1, 63,0);
        tracep->declQuad(c+23,"riscv_soc core__WIRE_5", false,-1, 63,0);
        tracep->declQuad(c+25,"riscv_soc core__WIRE_6", false,-1, 63,0);
        tracep->declQuad(c+27,"riscv_soc core__WIRE_7", false,-1, 63,0);
        tracep->declQuad(c+29,"riscv_soc core__WIRE_8", false,-1, 63,0);
        tracep->declQuad(c+31,"riscv_soc core__WIRE_9", false,-1, 63,0);
        tracep->declQuad(c+33,"riscv_soc core__WIRE_10", false,-1, 63,0);
        tracep->declQuad(c+35,"riscv_soc core__WIRE_11", false,-1, 63,0);
        tracep->declQuad(c+37,"riscv_soc core__WIRE_12", false,-1, 63,0);
        tracep->declQuad(c+39,"riscv_soc core__WIRE_13", false,-1, 63,0);
        tracep->declQuad(c+41,"riscv_soc core__WIRE_14", false,-1, 63,0);
        tracep->declQuad(c+43,"riscv_soc core__WIRE_15", false,-1, 63,0);
        tracep->declQuad(c+45,"riscv_soc core__WIRE_16", false,-1, 63,0);
        tracep->declQuad(c+47,"riscv_soc core__WIRE_17", false,-1, 63,0);
        tracep->declQuad(c+49,"riscv_soc core__WIRE_18", false,-1, 63,0);
        tracep->declQuad(c+51,"riscv_soc core__WIRE_19", false,-1, 63,0);
        tracep->declQuad(c+53,"riscv_soc core__WIRE_20", false,-1, 63,0);
        tracep->declQuad(c+55,"riscv_soc core__WIRE_21", false,-1, 63,0);
        tracep->declQuad(c+57,"riscv_soc core__WIRE_22", false,-1, 63,0);
        tracep->declQuad(c+59,"riscv_soc core__WIRE_23", false,-1, 63,0);
        tracep->declQuad(c+61,"riscv_soc core__WIRE_24", false,-1, 63,0);
        tracep->declQuad(c+63,"riscv_soc core__WIRE_25", false,-1, 63,0);
        tracep->declQuad(c+65,"riscv_soc core__WIRE_26", false,-1, 63,0);
        tracep->declQuad(c+67,"riscv_soc core__WIRE_27", false,-1, 63,0);
        tracep->declQuad(c+69,"riscv_soc core__WIRE_28", false,-1, 63,0);
        tracep->declQuad(c+71,"riscv_soc core__WIRE_29", false,-1, 63,0);
        tracep->declQuad(c+73,"riscv_soc core__WIRE_30", false,-1, 63,0);
        tracep->declQuad(c+75,"riscv_soc core__WIRE_31", false,-1, 63,0);
        tracep->declBit(c+278,"riscv_soc axi_ram_clock", false,-1);
        tracep->declQuad(c+7,"riscv_soc axi_ram_io_raddr", false,-1, 63,0);
        tracep->declQuad(c+1,"riscv_soc axi_ram_io_rdata", false,-1, 63,0);
        tracep->declQuad(c+3,"riscv_soc axi_ram_io_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc axi_ram_io_wdata", false,-1, 63,0);
        tracep->declBus(c+10,"riscv_soc axi_ram_io_wstrb", false,-1, 7,0);
        tracep->declBit(c+9,"riscv_soc axi_ram_io_wen", false,-1);
        tracep->declBus(c+14,"riscv_soc DIFFTEST_INST", false,-1, 31,0);
        tracep->declQuad(c+77,"riscv_soc difftest_inst", false,-1, 63,0);
        tracep->declBit(c+278,"riscv_soc core clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core reset", false,-1);
        tracep->declQuad(c+1,"riscv_soc core io_in_rdata", false,-1, 63,0);
        tracep->declQuad(c+3,"riscv_soc core io_out_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc core io_out_wdata", false,-1, 63,0);
        tracep->declQuad(c+7,"riscv_soc core io_out_raddr", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core io_out_wen", false,-1);
        tracep->declBus(c+10,"riscv_soc core io_out_wstrb", false,-1, 7,0);
        tracep->declBit(c+11,"riscv_soc core difftest_commit", false,-1);
        tracep->declQuad(c+12,"riscv_soc core difftest_pc", false,-1, 63,0);
        tracep->declBus(c+14,"riscv_soc core difftest_inst", false,-1, 31,0);
        tracep->declQuad(c+79,"riscv_soc core i_cache_io_cpu_in_addr", false,-1, 63,0);
        tracep->declQuad(c+348,"riscv_soc core i_cache_io_cpu_in_wdata", false,-1, 63,0);
        tracep->declBit(c+350,"riscv_soc core i_cache_io_cpu_in_is_w", false,-1);
        tracep->declBit(c+81,"riscv_soc core i_cache_io_cpu_in_avalid", false,-1);
        tracep->declBus(c+351,"riscv_soc core i_cache_io_cpu_in_wstrb", false,-1, 7,0);
        tracep->declQuad(c+82,"riscv_soc core i_cache_io_cpu_out_rdata", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core i_cache_io_cpu_out_rvalid", false,-1);
        tracep->declBit(c+85,"riscv_soc core i_cache_io_cpu_out_w_ok", false,-1);
        tracep->declQuad(c+82,"riscv_soc core i_cache_io_bus_in_data", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core i_cache_io_bus_in_valid", false,-1);
        tracep->declQuad(c+79,"riscv_soc core i_cache_io_bus_out_waddr", false,-1, 63,0);
        tracep->declQuad(c+348,"riscv_soc core i_cache_io_bus_out_wdata", false,-1, 63,0);
        tracep->declBit(c+350,"riscv_soc core i_cache_io_bus_out_wvalid", false,-1);
        tracep->declQuad(c+79,"riscv_soc core i_cache_io_bus_out_raddr", false,-1, 63,0);
        tracep->declBit(c+81,"riscv_soc core i_cache_io_bus_out_avalid", false,-1);
        tracep->declBus(c+351,"riscv_soc core i_cache_io_bus_out_wstrb", false,-1, 7,0);
        tracep->declQuad(c+3,"riscv_soc core d_cache_io_cpu_in_addr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc core d_cache_io_cpu_in_wdata", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core d_cache_io_cpu_in_is_w", false,-1);
        tracep->declBit(c+86,"riscv_soc core d_cache_io_cpu_in_avalid", false,-1);
        tracep->declBus(c+10,"riscv_soc core d_cache_io_cpu_in_wstrb", false,-1, 7,0);
        tracep->declQuad(c+82,"riscv_soc core d_cache_io_cpu_out_rdata", false,-1, 63,0);
        tracep->declBit(c+87,"riscv_soc core d_cache_io_cpu_out_rvalid", false,-1);
        tracep->declBit(c+88,"riscv_soc core d_cache_io_cpu_out_w_ok", false,-1);
        tracep->declQuad(c+82,"riscv_soc core d_cache_io_bus_in_data", false,-1, 63,0);
        tracep->declBit(c+87,"riscv_soc core d_cache_io_bus_in_valid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core d_cache_io_bus_out_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc core d_cache_io_bus_out_wdata", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core d_cache_io_bus_out_wvalid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core d_cache_io_bus_out_raddr", false,-1, 63,0);
        tracep->declBit(c+86,"riscv_soc core d_cache_io_bus_out_avalid", false,-1);
        tracep->declBus(c+10,"riscv_soc core d_cache_io_bus_out_wstrb", false,-1, 7,0);
        tracep->declBit(c+278,"riscv_soc core fetch_clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core fetch_reset", false,-1);
        tracep->declQuad(c+82,"riscv_soc core fetch_io_in_inst", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core fetch_io_in_valid", false,-1);
        tracep->declBit(c+89,"riscv_soc core fetch_io_in_de_stall", false,-1);
        tracep->declBit(c+90,"riscv_soc core fetch_io_in_wb_stall", false,-1);
        tracep->declQuad(c+91,"riscv_soc core fetch_io_in_next_pc", false,-1, 63,0);
        tracep->declBit(c+93,"riscv_soc core fetch_io_in_valid_next_pc", false,-1);
        tracep->declBit(c+94,"riscv_soc core fetch_io_in_flush", false,-1);
        tracep->declQuad(c+79,"riscv_soc core fetch_io_out_pc0", false,-1, 63,0);
        tracep->declBit(c+81,"riscv_soc core fetch_io_out_rvalid", false,-1);
        tracep->declQuad(c+95,"riscv_soc core fetch_io_out_pc1", false,-1, 63,0);
        tracep->declBus(c+97,"riscv_soc core fetch_io_out_inst", false,-1, 31,0);
        tracep->declBit(c+278,"riscv_soc core execute_clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core execute_reset", false,-1);
        tracep->declBus(c+98,"riscv_soc core execute_io_in_opType", false,-1, 2,0);
        tracep->declBus(c+99,"riscv_soc core execute_io_in_exuType", false,-1, 5,0);
        tracep->declBus(c+100,"riscv_soc core execute_io_in_rs1_addr", false,-1, 4,0);
        tracep->declQuad(c+101,"riscv_soc core execute_io_in_rs1_data", false,-1, 63,0);
        tracep->declBus(c+103,"riscv_soc core execute_io_in_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+104,"riscv_soc core execute_io_in_rs2_data", false,-1, 63,0);
        tracep->declQuad(c+106,"riscv_soc core execute_io_in_imm_data", false,-1, 63,0);
        tracep->declQuad(c+108,"riscv_soc core execute_io_in_pc", false,-1, 63,0);
        tracep->declBus(c+110,"riscv_soc core execute_io_in_inst", false,-1, 31,0);
        tracep->declBus(c+111,"riscv_soc core execute_io_in_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+112,"riscv_soc core execute_io_in_wb_result_data", false,-1, 63,0);
        tracep->declBus(c+114,"riscv_soc core execute_io_in_wb_rs_addr", false,-1, 4,0);
        tracep->declBit(c+115,"riscv_soc core execute_io_in_wb_w_rs_en", false,-1);
        tracep->declBit(c+90,"riscv_soc core execute_io_in_stall", false,-1);
        tracep->declBus(c+116,"riscv_soc core execute_io_out_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+117,"riscv_soc core execute_io_out_rs_data", false,-1, 63,0);
        tracep->declBit(c+119,"riscv_soc core execute_io_out_w_rs_en", false,-1);
        tracep->declBus(c+120,"riscv_soc core execute_io_out_exuType", false,-1, 5,0);
        tracep->declQuad(c+121,"riscv_soc core execute_io_out_pc", false,-1, 63,0);
        tracep->declBus(c+123,"riscv_soc core execute_io_out_inst", false,-1, 31,0);
        tracep->declBus(c+124,"riscv_soc core execute_io_out_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+125,"riscv_soc core execute_io_out_rs2_data", false,-1, 63,0);
        tracep->declQuad(c+127,"riscv_soc core execute_io_out_mem_addr", false,-1, 63,0);
        tracep->declBit(c+129,"riscv_soc core execute_io_out_mem_avalid", false,-1);
        tracep->declBit(c+130,"riscv_soc core execute_io_out_w_mem_en", false,-1);
        tracep->declQuad(c+91,"riscv_soc core execute_io_out_next_pc", false,-1, 63,0);
        tracep->declBit(c+93,"riscv_soc core execute_io_out_valid_next_pc", false,-1);
        tracep->declBit(c+94,"riscv_soc core execute_io_out_flush", false,-1);
        tracep->declBit(c+278,"riscv_soc core decode_clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core decode_reset", false,-1);
        tracep->declBus(c+97,"riscv_soc core decode_io_in_inst", false,-1, 31,0);
        tracep->declQuad(c+95,"riscv_soc core decode_io_in_pc", false,-1, 63,0);
        tracep->declBus(c+114,"riscv_soc core decode_io_in_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+112,"riscv_soc core decode_io_in_result_data", false,-1, 63,0);
        tracep->declBit(c+115,"riscv_soc core decode_io_in_w_rs_en", false,-1);
        tracep->declBit(c+90,"riscv_soc core decode_io_in_stall", false,-1);
        tracep->declBit(c+94,"riscv_soc core decode_io_in_flush", false,-1);
        tracep->declQuad(c+101,"riscv_soc core decode_io_out_rs1_data", false,-1, 63,0);
        tracep->declQuad(c+104,"riscv_soc core decode_io_out_rs2_data", false,-1, 63,0);
        tracep->declBus(c+100,"riscv_soc core decode_io_out_rs1_addr", false,-1, 4,0);
        tracep->declBus(c+103,"riscv_soc core decode_io_out_rs2_addr", false,-1, 4,0);
        tracep->declBus(c+111,"riscv_soc core decode_io_out_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+106,"riscv_soc core decode_io_out_imm_data", false,-1, 63,0);
        tracep->declBus(c+98,"riscv_soc core decode_io_out_opType", false,-1, 2,0);
        tracep->declBus(c+99,"riscv_soc core decode_io_out_exuType", false,-1, 5,0);
        tracep->declQuad(c+108,"riscv_soc core decode_io_out_pc", false,-1, 63,0);
        tracep->declBus(c+110,"riscv_soc core decode_io_out_inst", false,-1, 31,0);
        tracep->declBit(c+89,"riscv_soc core decode_io_out_stall", false,-1);
        tracep->declQuad(c+348,"riscv_soc core decode__WIRE_0_0", false,-1, 63,0);
        tracep->declQuad(c+15,"riscv_soc core decode__WIRE_0_1", false,-1, 63,0);
        tracep->declQuad(c+17,"riscv_soc core decode__WIRE_0_2", false,-1, 63,0);
        tracep->declQuad(c+19,"riscv_soc core decode__WIRE_0_3", false,-1, 63,0);
        tracep->declQuad(c+21,"riscv_soc core decode__WIRE_0_4", false,-1, 63,0);
        tracep->declQuad(c+23,"riscv_soc core decode__WIRE_0_5", false,-1, 63,0);
        tracep->declQuad(c+25,"riscv_soc core decode__WIRE_0_6", false,-1, 63,0);
        tracep->declQuad(c+27,"riscv_soc core decode__WIRE_0_7", false,-1, 63,0);
        tracep->declQuad(c+29,"riscv_soc core decode__WIRE_0_8", false,-1, 63,0);
        tracep->declQuad(c+31,"riscv_soc core decode__WIRE_0_9", false,-1, 63,0);
        tracep->declQuad(c+33,"riscv_soc core decode__WIRE_0_10", false,-1, 63,0);
        tracep->declQuad(c+35,"riscv_soc core decode__WIRE_0_11", false,-1, 63,0);
        tracep->declQuad(c+37,"riscv_soc core decode__WIRE_0_12", false,-1, 63,0);
        tracep->declQuad(c+39,"riscv_soc core decode__WIRE_0_13", false,-1, 63,0);
        tracep->declQuad(c+41,"riscv_soc core decode__WIRE_0_14", false,-1, 63,0);
        tracep->declQuad(c+43,"riscv_soc core decode__WIRE_0_15", false,-1, 63,0);
        tracep->declQuad(c+45,"riscv_soc core decode__WIRE_0_16", false,-1, 63,0);
        tracep->declQuad(c+47,"riscv_soc core decode__WIRE_0_17", false,-1, 63,0);
        tracep->declQuad(c+49,"riscv_soc core decode__WIRE_0_18", false,-1, 63,0);
        tracep->declQuad(c+51,"riscv_soc core decode__WIRE_0_19", false,-1, 63,0);
        tracep->declQuad(c+53,"riscv_soc core decode__WIRE_0_20", false,-1, 63,0);
        tracep->declQuad(c+55,"riscv_soc core decode__WIRE_0_21", false,-1, 63,0);
        tracep->declQuad(c+57,"riscv_soc core decode__WIRE_0_22", false,-1, 63,0);
        tracep->declQuad(c+59,"riscv_soc core decode__WIRE_0_23", false,-1, 63,0);
        tracep->declQuad(c+61,"riscv_soc core decode__WIRE_0_24", false,-1, 63,0);
        tracep->declQuad(c+63,"riscv_soc core decode__WIRE_0_25", false,-1, 63,0);
        tracep->declQuad(c+65,"riscv_soc core decode__WIRE_0_26", false,-1, 63,0);
        tracep->declQuad(c+67,"riscv_soc core decode__WIRE_0_27", false,-1, 63,0);
        tracep->declQuad(c+69,"riscv_soc core decode__WIRE_0_28", false,-1, 63,0);
        tracep->declQuad(c+71,"riscv_soc core decode__WIRE_0_29", false,-1, 63,0);
        tracep->declQuad(c+73,"riscv_soc core decode__WIRE_0_30", false,-1, 63,0);
        tracep->declQuad(c+75,"riscv_soc core decode__WIRE_0_31", false,-1, 63,0);
        tracep->declBit(c+278,"riscv_soc core write_back_clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core write_back_reset", false,-1);
        tracep->declBus(c+116,"riscv_soc core write_back_io_in_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+117,"riscv_soc core write_back_io_in_result_data", false,-1, 63,0);
        tracep->declBit(c+119,"riscv_soc core write_back_io_in_w_rs_en", false,-1);
        tracep->declBus(c+120,"riscv_soc core write_back_io_in_exuType", false,-1, 5,0);
        tracep->declBus(c+124,"riscv_soc core write_back_io_in_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+125,"riscv_soc core write_back_io_in_rs2_data", false,-1, 63,0);
        tracep->declQuad(c+127,"riscv_soc core write_back_io_in_mem_addr", false,-1, 63,0);
        tracep->declBit(c+129,"riscv_soc core write_back_io_in_mem_avalid", false,-1);
        tracep->declBit(c+130,"riscv_soc core write_back_io_in_w_mem_en", false,-1);
        tracep->declQuad(c+121,"riscv_soc core write_back_io_in_pc", false,-1, 63,0);
        tracep->declBus(c+123,"riscv_soc core write_back_io_in_inst", false,-1, 31,0);
        tracep->declQuad(c+82,"riscv_soc core write_back_io_in_mem_data", false,-1, 63,0);
        tracep->declBit(c+87,"riscv_soc core write_back_io_in_mem_valid", false,-1);
        tracep->declBit(c+88,"riscv_soc core write_back_io_in_w_ok", false,-1);
        tracep->declBus(c+114,"riscv_soc core write_back_io_out_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+112,"riscv_soc core write_back_io_out_result_data", false,-1, 63,0);
        tracep->declBit(c+115,"riscv_soc core write_back_io_out_w_rs_en", false,-1);
        tracep->declQuad(c+5,"riscv_soc core write_back_io_out_mem_wdata", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core write_back_io_out_mem_wvalid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core write_back_io_out_mem_addr", false,-1, 63,0);
        tracep->declBit(c+86,"riscv_soc core write_back_io_out_mem_avalid", false,-1);
        tracep->declBus(c+10,"riscv_soc core write_back_io_out_mem_wstrb", false,-1, 7,0);
        tracep->declBit(c+90,"riscv_soc core write_back_io_out_stall", false,-1);
        tracep->declBit(c+11,"riscv_soc core write_back_difftest_commit_0", false,-1);
        tracep->declQuad(c+12,"riscv_soc core write_back_difftest_pc_0", false,-1, 63,0);
        tracep->declBus(c+14,"riscv_soc core write_back_difftest_inst_0", false,-1, 31,0);
        tracep->declBit(c+131,"riscv_soc core is_read_mem", false,-1);
        tracep->declBit(c+132,"riscv_soc core is_read_inst", false,-1);
        tracep->declQuad(c+82,"riscv_soc core tem_reg_rdata", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core tem_reg_is_read_inst", false,-1);
        tracep->declBit(c+87,"riscv_soc core tem_reg_is_read_mem", false,-1);
        tracep->declQuad(c+79,"riscv_soc core i_cache io_cpu_in_addr", false,-1, 63,0);
        tracep->declQuad(c+348,"riscv_soc core i_cache io_cpu_in_wdata", false,-1, 63,0);
        tracep->declBit(c+350,"riscv_soc core i_cache io_cpu_in_is_w", false,-1);
        tracep->declBit(c+81,"riscv_soc core i_cache io_cpu_in_avalid", false,-1);
        tracep->declBus(c+351,"riscv_soc core i_cache io_cpu_in_wstrb", false,-1, 7,0);
        tracep->declQuad(c+82,"riscv_soc core i_cache io_cpu_out_rdata", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core i_cache io_cpu_out_rvalid", false,-1);
        tracep->declBit(c+85,"riscv_soc core i_cache io_cpu_out_w_ok", false,-1);
        tracep->declQuad(c+82,"riscv_soc core i_cache io_bus_in_data", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core i_cache io_bus_in_valid", false,-1);
        tracep->declQuad(c+79,"riscv_soc core i_cache io_bus_out_waddr", false,-1, 63,0);
        tracep->declQuad(c+348,"riscv_soc core i_cache io_bus_out_wdata", false,-1, 63,0);
        tracep->declBit(c+350,"riscv_soc core i_cache io_bus_out_wvalid", false,-1);
        tracep->declQuad(c+79,"riscv_soc core i_cache io_bus_out_raddr", false,-1, 63,0);
        tracep->declBit(c+81,"riscv_soc core i_cache io_bus_out_avalid", false,-1);
        tracep->declBus(c+351,"riscv_soc core i_cache io_bus_out_wstrb", false,-1, 7,0);
        tracep->declQuad(c+3,"riscv_soc core d_cache io_cpu_in_addr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc core d_cache io_cpu_in_wdata", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core d_cache io_cpu_in_is_w", false,-1);
        tracep->declBit(c+86,"riscv_soc core d_cache io_cpu_in_avalid", false,-1);
        tracep->declBus(c+10,"riscv_soc core d_cache io_cpu_in_wstrb", false,-1, 7,0);
        tracep->declQuad(c+82,"riscv_soc core d_cache io_cpu_out_rdata", false,-1, 63,0);
        tracep->declBit(c+87,"riscv_soc core d_cache io_cpu_out_rvalid", false,-1);
        tracep->declBit(c+88,"riscv_soc core d_cache io_cpu_out_w_ok", false,-1);
        tracep->declQuad(c+82,"riscv_soc core d_cache io_bus_in_data", false,-1, 63,0);
        tracep->declBit(c+87,"riscv_soc core d_cache io_bus_in_valid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core d_cache io_bus_out_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc core d_cache io_bus_out_wdata", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core d_cache io_bus_out_wvalid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core d_cache io_bus_out_raddr", false,-1, 63,0);
        tracep->declBit(c+86,"riscv_soc core d_cache io_bus_out_avalid", false,-1);
        tracep->declBus(c+10,"riscv_soc core d_cache io_bus_out_wstrb", false,-1, 7,0);
        tracep->declBit(c+278,"riscv_soc core fetch clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core fetch reset", false,-1);
        tracep->declQuad(c+82,"riscv_soc core fetch io_in_inst", false,-1, 63,0);
        tracep->declBit(c+84,"riscv_soc core fetch io_in_valid", false,-1);
        tracep->declBit(c+89,"riscv_soc core fetch io_in_de_stall", false,-1);
        tracep->declBit(c+90,"riscv_soc core fetch io_in_wb_stall", false,-1);
        tracep->declQuad(c+91,"riscv_soc core fetch io_in_next_pc", false,-1, 63,0);
        tracep->declBit(c+93,"riscv_soc core fetch io_in_valid_next_pc", false,-1);
        tracep->declBit(c+94,"riscv_soc core fetch io_in_flush", false,-1);
        tracep->declQuad(c+79,"riscv_soc core fetch io_out_pc0", false,-1, 63,0);
        tracep->declBit(c+81,"riscv_soc core fetch io_out_rvalid", false,-1);
        tracep->declQuad(c+95,"riscv_soc core fetch io_out_pc1", false,-1, 63,0);
        tracep->declBus(c+97,"riscv_soc core fetch io_out_inst", false,-1, 31,0);
        tracep->declBit(c+133,"riscv_soc core fetch stall", false,-1);
        tracep->declQuad(c+79,"riscv_soc core fetch regPC", false,-1, 63,0);
        tracep->declBit(c+134,"riscv_soc core fetch pc_valid", false,-1);
        tracep->declBus(c+135,"riscv_soc core fetch regInst", false,-1, 31,0);
        tracep->declQuad(c+95,"riscv_soc core fetch regTempPC", false,-1, 63,0);
        tracep->declBit(c+278,"riscv_soc core execute clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core execute reset", false,-1);
        tracep->declBus(c+98,"riscv_soc core execute io_in_opType", false,-1, 2,0);
        tracep->declBus(c+99,"riscv_soc core execute io_in_exuType", false,-1, 5,0);
        tracep->declBus(c+100,"riscv_soc core execute io_in_rs1_addr", false,-1, 4,0);
        tracep->declQuad(c+101,"riscv_soc core execute io_in_rs1_data", false,-1, 63,0);
        tracep->declBus(c+103,"riscv_soc core execute io_in_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+104,"riscv_soc core execute io_in_rs2_data", false,-1, 63,0);
        tracep->declQuad(c+106,"riscv_soc core execute io_in_imm_data", false,-1, 63,0);
        tracep->declQuad(c+108,"riscv_soc core execute io_in_pc", false,-1, 63,0);
        tracep->declBus(c+110,"riscv_soc core execute io_in_inst", false,-1, 31,0);
        tracep->declBus(c+111,"riscv_soc core execute io_in_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+112,"riscv_soc core execute io_in_wb_result_data", false,-1, 63,0);
        tracep->declBus(c+114,"riscv_soc core execute io_in_wb_rs_addr", false,-1, 4,0);
        tracep->declBit(c+115,"riscv_soc core execute io_in_wb_w_rs_en", false,-1);
        tracep->declBit(c+90,"riscv_soc core execute io_in_stall", false,-1);
        tracep->declBus(c+116,"riscv_soc core execute io_out_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+117,"riscv_soc core execute io_out_rs_data", false,-1, 63,0);
        tracep->declBit(c+119,"riscv_soc core execute io_out_w_rs_en", false,-1);
        tracep->declBus(c+120,"riscv_soc core execute io_out_exuType", false,-1, 5,0);
        tracep->declQuad(c+121,"riscv_soc core execute io_out_pc", false,-1, 63,0);
        tracep->declBus(c+123,"riscv_soc core execute io_out_inst", false,-1, 31,0);
        tracep->declBus(c+124,"riscv_soc core execute io_out_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+125,"riscv_soc core execute io_out_rs2_data", false,-1, 63,0);
        tracep->declQuad(c+127,"riscv_soc core execute io_out_mem_addr", false,-1, 63,0);
        tracep->declBit(c+129,"riscv_soc core execute io_out_mem_avalid", false,-1);
        tracep->declBit(c+130,"riscv_soc core execute io_out_w_mem_en", false,-1);
        tracep->declQuad(c+91,"riscv_soc core execute io_out_next_pc", false,-1, 63,0);
        tracep->declBit(c+93,"riscv_soc core execute io_out_valid_next_pc", false,-1);
        tracep->declBit(c+94,"riscv_soc core execute io_out_flush", false,-1);
        tracep->declBus(c+99,"riscv_soc core execute alu_exu_io_exuType", false,-1, 5,0);
        tracep->declQuad(c+136,"riscv_soc core execute alu_exu_io_op_data1", false,-1, 63,0);
        tracep->declQuad(c+138,"riscv_soc core execute alu_exu_io_op_data2", false,-1, 63,0);
        tracep->declQuad(c+106,"riscv_soc core execute alu_exu_io_op_imm", false,-1, 63,0);
        tracep->declQuad(c+108,"riscv_soc core execute alu_exu_io_op_pc", false,-1, 63,0);
        tracep->declQuad(c+140,"riscv_soc core execute alu_exu_io_result_data", false,-1, 63,0);
        tracep->declQuad(c+142,"riscv_soc core execute alu_exu_io_result_pc", false,-1, 63,0);
        tracep->declBit(c+144,"riscv_soc core execute alu_exu_io_next_pc_valid", false,-1);
        tracep->declBit(c+145,"riscv_soc core execute alu_exu_io_w_rs_en", false,-1);
        tracep->declBit(c+146,"riscv_soc core execute lsu_exu_io_valid", false,-1);
        tracep->declBus(c+99,"riscv_soc core execute lsu_exu_io_exuType", false,-1, 5,0);
        tracep->declQuad(c+136,"riscv_soc core execute lsu_exu_io_rs1_data", false,-1, 63,0);
        tracep->declQuad(c+106,"riscv_soc core execute lsu_exu_io_imm_data", false,-1, 63,0);
        tracep->declQuad(c+147,"riscv_soc core execute lsu_exu_io_address_result", false,-1, 63,0);
        tracep->declBit(c+146,"riscv_soc core execute lsu_exu_io_avalid", false,-1);
        tracep->declBit(c+149,"riscv_soc core execute lsu_exu_io_w_mem_en", false,-1);
        tracep->declQuad(c+150,"riscv_soc core execute reg_rs_addr", false,-1, 63,0);
        tracep->declQuad(c+117,"riscv_soc core execute reg_rs_data", false,-1, 63,0);
        tracep->declQuad(c+91,"riscv_soc core execute reg_next_pc", false,-1, 63,0);
        tracep->declBit(c+152,"riscv_soc core execute reg_flush", false,-1);
        tracep->declBit(c+153,"riscv_soc core execute reg_w_rs_en", false,-1);
        tracep->declBus(c+154,"riscv_soc core execute reg_exuType", false,-1, 5,0);
        tracep->declQuad(c+121,"riscv_soc core execute reg_pc", false,-1, 63,0);
        tracep->declBus(c+123,"riscv_soc core execute reg_inst", false,-1, 31,0);
        tracep->declQuad(c+125,"riscv_soc core execute reg_rs2_data", false,-1, 63,0);
        tracep->declBus(c+124,"riscv_soc core execute reg_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+127,"riscv_soc core execute reg_mem_addr", false,-1, 63,0);
        tracep->declBit(c+155,"riscv_soc core execute reg_mem_avalid", false,-1);
        tracep->declBit(c+156,"riscv_soc core execute reg_w_mem_en", false,-1);
        tracep->declBus(c+157,"riscv_soc core execute valid", false,-1, 3,0);
        tracep->declArray(c+158,"riscv_soc core execute temp_w_en_and_rs_data", false,-1, 64,0);
        tracep->declBit(c+161,"riscv_soc core execute w_rs_en", false,-1);
        tracep->declQuad(c+162,"riscv_soc core execute rs_data", false,-1, 63,0);
        tracep->declBus(c+99,"riscv_soc core execute alu_exu io_exuType", false,-1, 5,0);
        tracep->declQuad(c+136,"riscv_soc core execute alu_exu io_op_data1", false,-1, 63,0);
        tracep->declQuad(c+138,"riscv_soc core execute alu_exu io_op_data2", false,-1, 63,0);
        tracep->declQuad(c+106,"riscv_soc core execute alu_exu io_op_imm", false,-1, 63,0);
        tracep->declQuad(c+108,"riscv_soc core execute alu_exu io_op_pc", false,-1, 63,0);
        tracep->declQuad(c+140,"riscv_soc core execute alu_exu io_result_data", false,-1, 63,0);
        tracep->declQuad(c+142,"riscv_soc core execute alu_exu io_result_pc", false,-1, 63,0);
        tracep->declBit(c+144,"riscv_soc core execute alu_exu io_next_pc_valid", false,-1);
        tracep->declBit(c+145,"riscv_soc core execute alu_exu io_w_rs_en", false,-1);
        tracep->declQuad(c+164,"riscv_soc core execute alu_exu rs2_data", false,-1, 63,0);
        tracep->declArray(c+166,"riscv_soc core execute alu_exu subresult", false,-1, 64,0);
        tracep->declBit(c+169,"riscv_soc core execute alu_exu u_rs1_l_rs2", false,-1);
        tracep->declBit(c+170,"riscv_soc core execute alu_exu s_rs1_l_rs2", false,-1);
        tracep->declQuad(c+171,"riscv_soc core execute alu_exu sllw_temp", false,-1, 62,0);
        tracep->declBus(c+173,"riscv_soc core execute alu_exu srlw_temp", false,-1, 31,0);
        tracep->declBus(c+174,"riscv_soc core execute alu_exu sraw_temp", false,-1, 31,0);
        tracep->declArray(c+175,"riscv_soc core execute alu_exu temp_result_data", false,-1, 127,0);
        tracep->declArray(c+179,"riscv_soc core execute alu_exu next_pc3", false,-1, 64,0);
        tracep->declArray(c+182,"riscv_soc core execute alu_exu temp_result_pc", false,-1, 64,0);
        tracep->declBit(c+146,"riscv_soc core execute lsu_exu io_valid", false,-1);
        tracep->declBus(c+99,"riscv_soc core execute lsu_exu io_exuType", false,-1, 5,0);
        tracep->declQuad(c+136,"riscv_soc core execute lsu_exu io_rs1_data", false,-1, 63,0);
        tracep->declQuad(c+106,"riscv_soc core execute lsu_exu io_imm_data", false,-1, 63,0);
        tracep->declQuad(c+147,"riscv_soc core execute lsu_exu io_address_result", false,-1, 63,0);
        tracep->declBit(c+146,"riscv_soc core execute lsu_exu io_avalid", false,-1);
        tracep->declBit(c+149,"riscv_soc core execute lsu_exu io_w_mem_en", false,-1);
        tracep->declBit(c+278,"riscv_soc core decode clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core decode reset", false,-1);
        tracep->declBus(c+97,"riscv_soc core decode io_in_inst", false,-1, 31,0);
        tracep->declQuad(c+95,"riscv_soc core decode io_in_pc", false,-1, 63,0);
        tracep->declBus(c+114,"riscv_soc core decode io_in_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+112,"riscv_soc core decode io_in_result_data", false,-1, 63,0);
        tracep->declBit(c+115,"riscv_soc core decode io_in_w_rs_en", false,-1);
        tracep->declBit(c+90,"riscv_soc core decode io_in_stall", false,-1);
        tracep->declBit(c+94,"riscv_soc core decode io_in_flush", false,-1);
        tracep->declQuad(c+101,"riscv_soc core decode io_out_rs1_data", false,-1, 63,0);
        tracep->declQuad(c+104,"riscv_soc core decode io_out_rs2_data", false,-1, 63,0);
        tracep->declBus(c+100,"riscv_soc core decode io_out_rs1_addr", false,-1, 4,0);
        tracep->declBus(c+103,"riscv_soc core decode io_out_rs2_addr", false,-1, 4,0);
        tracep->declBus(c+111,"riscv_soc core decode io_out_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+106,"riscv_soc core decode io_out_imm_data", false,-1, 63,0);
        tracep->declBus(c+98,"riscv_soc core decode io_out_opType", false,-1, 2,0);
        tracep->declBus(c+99,"riscv_soc core decode io_out_exuType", false,-1, 5,0);
        tracep->declQuad(c+108,"riscv_soc core decode io_out_pc", false,-1, 63,0);
        tracep->declBus(c+110,"riscv_soc core decode io_out_inst", false,-1, 31,0);
        tracep->declBit(c+89,"riscv_soc core decode io_out_stall", false,-1);
        {int i; for (i=0; i<32; i++) {
                tracep->declQuad(c+185+i*2,"riscv_soc core decode regfile", true,(i+0), 63,0);}}
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_en", false,-1);
        tracep->declBus(c+353,"riscv_soc core decode regfile_MPORT_addr", false,-1, 4,0);
        tracep->declQuad(c+249,"riscv_soc core decode regfile_MPORT_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_1_en", false,-1);
        tracep->declBus(c+354,"riscv_soc core decode regfile_MPORT_1_addr", false,-1, 4,0);
        tracep->declQuad(c+15,"riscv_soc core decode regfile_MPORT_1_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_2_en", false,-1);
        tracep->declBus(c+355,"riscv_soc core decode regfile_MPORT_2_addr", false,-1, 4,0);
        tracep->declQuad(c+17,"riscv_soc core decode regfile_MPORT_2_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_3_en", false,-1);
        tracep->declBus(c+356,"riscv_soc core decode regfile_MPORT_3_addr", false,-1, 4,0);
        tracep->declQuad(c+19,"riscv_soc core decode regfile_MPORT_3_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_4_en", false,-1);
        tracep->declBus(c+357,"riscv_soc core decode regfile_MPORT_4_addr", false,-1, 4,0);
        tracep->declQuad(c+21,"riscv_soc core decode regfile_MPORT_4_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_5_en", false,-1);
        tracep->declBus(c+358,"riscv_soc core decode regfile_MPORT_5_addr", false,-1, 4,0);
        tracep->declQuad(c+23,"riscv_soc core decode regfile_MPORT_5_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_6_en", false,-1);
        tracep->declBus(c+359,"riscv_soc core decode regfile_MPORT_6_addr", false,-1, 4,0);
        tracep->declQuad(c+25,"riscv_soc core decode regfile_MPORT_6_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_7_en", false,-1);
        tracep->declBus(c+360,"riscv_soc core decode regfile_MPORT_7_addr", false,-1, 4,0);
        tracep->declQuad(c+27,"riscv_soc core decode regfile_MPORT_7_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_8_en", false,-1);
        tracep->declBus(c+361,"riscv_soc core decode regfile_MPORT_8_addr", false,-1, 4,0);
        tracep->declQuad(c+29,"riscv_soc core decode regfile_MPORT_8_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_9_en", false,-1);
        tracep->declBus(c+362,"riscv_soc core decode regfile_MPORT_9_addr", false,-1, 4,0);
        tracep->declQuad(c+31,"riscv_soc core decode regfile_MPORT_9_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_10_en", false,-1);
        tracep->declBus(c+363,"riscv_soc core decode regfile_MPORT_10_addr", false,-1, 4,0);
        tracep->declQuad(c+33,"riscv_soc core decode regfile_MPORT_10_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_11_en", false,-1);
        tracep->declBus(c+364,"riscv_soc core decode regfile_MPORT_11_addr", false,-1, 4,0);
        tracep->declQuad(c+35,"riscv_soc core decode regfile_MPORT_11_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_12_en", false,-1);
        tracep->declBus(c+365,"riscv_soc core decode regfile_MPORT_12_addr", false,-1, 4,0);
        tracep->declQuad(c+37,"riscv_soc core decode regfile_MPORT_12_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_13_en", false,-1);
        tracep->declBus(c+366,"riscv_soc core decode regfile_MPORT_13_addr", false,-1, 4,0);
        tracep->declQuad(c+39,"riscv_soc core decode regfile_MPORT_13_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_14_en", false,-1);
        tracep->declBus(c+367,"riscv_soc core decode regfile_MPORT_14_addr", false,-1, 4,0);
        tracep->declQuad(c+41,"riscv_soc core decode regfile_MPORT_14_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_15_en", false,-1);
        tracep->declBus(c+368,"riscv_soc core decode regfile_MPORT_15_addr", false,-1, 4,0);
        tracep->declQuad(c+43,"riscv_soc core decode regfile_MPORT_15_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_16_en", false,-1);
        tracep->declBus(c+369,"riscv_soc core decode regfile_MPORT_16_addr", false,-1, 4,0);
        tracep->declQuad(c+45,"riscv_soc core decode regfile_MPORT_16_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_17_en", false,-1);
        tracep->declBus(c+370,"riscv_soc core decode regfile_MPORT_17_addr", false,-1, 4,0);
        tracep->declQuad(c+47,"riscv_soc core decode regfile_MPORT_17_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_18_en", false,-1);
        tracep->declBus(c+371,"riscv_soc core decode regfile_MPORT_18_addr", false,-1, 4,0);
        tracep->declQuad(c+49,"riscv_soc core decode regfile_MPORT_18_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_19_en", false,-1);
        tracep->declBus(c+372,"riscv_soc core decode regfile_MPORT_19_addr", false,-1, 4,0);
        tracep->declQuad(c+51,"riscv_soc core decode regfile_MPORT_19_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_20_en", false,-1);
        tracep->declBus(c+373,"riscv_soc core decode regfile_MPORT_20_addr", false,-1, 4,0);
        tracep->declQuad(c+53,"riscv_soc core decode regfile_MPORT_20_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_21_en", false,-1);
        tracep->declBus(c+374,"riscv_soc core decode regfile_MPORT_21_addr", false,-1, 4,0);
        tracep->declQuad(c+55,"riscv_soc core decode regfile_MPORT_21_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_22_en", false,-1);
        tracep->declBus(c+375,"riscv_soc core decode regfile_MPORT_22_addr", false,-1, 4,0);
        tracep->declQuad(c+57,"riscv_soc core decode regfile_MPORT_22_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_23_en", false,-1);
        tracep->declBus(c+376,"riscv_soc core decode regfile_MPORT_23_addr", false,-1, 4,0);
        tracep->declQuad(c+59,"riscv_soc core decode regfile_MPORT_23_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_24_en", false,-1);
        tracep->declBus(c+377,"riscv_soc core decode regfile_MPORT_24_addr", false,-1, 4,0);
        tracep->declQuad(c+61,"riscv_soc core decode regfile_MPORT_24_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_25_en", false,-1);
        tracep->declBus(c+378,"riscv_soc core decode regfile_MPORT_25_addr", false,-1, 4,0);
        tracep->declQuad(c+63,"riscv_soc core decode regfile_MPORT_25_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_26_en", false,-1);
        tracep->declBus(c+379,"riscv_soc core decode regfile_MPORT_26_addr", false,-1, 4,0);
        tracep->declQuad(c+65,"riscv_soc core decode regfile_MPORT_26_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_27_en", false,-1);
        tracep->declBus(c+380,"riscv_soc core decode regfile_MPORT_27_addr", false,-1, 4,0);
        tracep->declQuad(c+67,"riscv_soc core decode regfile_MPORT_27_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_28_en", false,-1);
        tracep->declBus(c+381,"riscv_soc core decode regfile_MPORT_28_addr", false,-1, 4,0);
        tracep->declQuad(c+69,"riscv_soc core decode regfile_MPORT_28_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_29_en", false,-1);
        tracep->declBus(c+382,"riscv_soc core decode regfile_MPORT_29_addr", false,-1, 4,0);
        tracep->declQuad(c+71,"riscv_soc core decode regfile_MPORT_29_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_30_en", false,-1);
        tracep->declBus(c+383,"riscv_soc core decode regfile_MPORT_30_addr", false,-1, 4,0);
        tracep->declQuad(c+73,"riscv_soc core decode regfile_MPORT_30_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_31_en", false,-1);
        tracep->declBus(c+384,"riscv_soc core decode regfile_MPORT_31_addr", false,-1, 4,0);
        tracep->declQuad(c+75,"riscv_soc core decode regfile_MPORT_31_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_rs1_data_MPORT_en", false,-1);
        tracep->declBus(c+251,"riscv_soc core decode regfile_rs1_data_MPORT_addr", false,-1, 4,0);
        tracep->declQuad(c+252,"riscv_soc core decode regfile_rs1_data_MPORT_data", false,-1, 63,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_rs2_data_MPORT_en", false,-1);
        tracep->declBus(c+254,"riscv_soc core decode regfile_rs2_data_MPORT_addr", false,-1, 4,0);
        tracep->declQuad(c+255,"riscv_soc core decode regfile_rs2_data_MPORT_data", false,-1, 63,0);
        tracep->declQuad(c+112,"riscv_soc core decode regfile_MPORT_32_data", false,-1, 63,0);
        tracep->declBus(c+114,"riscv_soc core decode regfile_MPORT_32_addr", false,-1, 4,0);
        tracep->declBit(c+352,"riscv_soc core decode regfile_MPORT_32_mask", false,-1);
        tracep->declBit(c+115,"riscv_soc core decode regfile_MPORT_32_en", false,-1);
        tracep->declQuad(c+101,"riscv_soc core decode reg_rs1_data", false,-1, 63,0);
        tracep->declQuad(c+104,"riscv_soc core decode reg_rs2_data", false,-1, 63,0);
        tracep->declBus(c+111,"riscv_soc core decode reg_dest_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+106,"riscv_soc core decode reg_imm", false,-1, 63,0);
        tracep->declBus(c+257,"riscv_soc core decode reg_opType", false,-1, 2,0);
        tracep->declBus(c+258,"riscv_soc core decode reg_exuType", false,-1, 5,0);
        tracep->declQuad(c+108,"riscv_soc core decode reg_pc", false,-1, 63,0);
        tracep->declBus(c+110,"riscv_soc core decode reg_inst", false,-1, 31,0);
        tracep->declBus(c+100,"riscv_soc core decode reg_rs1_addr", false,-1, 4,0);
        tracep->declBus(c+103,"riscv_soc core decode reg_rs2_addr", false,-1, 4,0);
        tracep->declBit(c+89,"riscv_soc core decode reg_stall", false,-1);
        tracep->declBit(c+133,"riscv_soc core decode stall", false,-1);
        tracep->declBus(c+259,"riscv_soc core decode instType", false,-1, 3,0);
        tracep->declBus(c+254,"riscv_soc core decode rs2_addr", false,-1, 4,0);
        tracep->declBus(c+251,"riscv_soc core decode rs1_addr", false,-1, 4,0);
        tracep->declBus(c+260,"riscv_soc core decode dest_rs_addr", false,-1, 4,0);
        tracep->declBus(c+261,"riscv_soc core decode csr_addr", false,-1, 11,0);
        tracep->declBit(c+262,"riscv_soc core decode temp_stall", false,-1);
        tracep->declBit(c+278,"riscv_soc core write_back clock", false,-1);
        tracep->declBit(c+279,"riscv_soc core write_back reset", false,-1);
        tracep->declBus(c+116,"riscv_soc core write_back io_in_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+117,"riscv_soc core write_back io_in_result_data", false,-1, 63,0);
        tracep->declBit(c+119,"riscv_soc core write_back io_in_w_rs_en", false,-1);
        tracep->declBus(c+120,"riscv_soc core write_back io_in_exuType", false,-1, 5,0);
        tracep->declBus(c+124,"riscv_soc core write_back io_in_rs2_addr", false,-1, 4,0);
        tracep->declQuad(c+125,"riscv_soc core write_back io_in_rs2_data", false,-1, 63,0);
        tracep->declQuad(c+127,"riscv_soc core write_back io_in_mem_addr", false,-1, 63,0);
        tracep->declBit(c+129,"riscv_soc core write_back io_in_mem_avalid", false,-1);
        tracep->declBit(c+130,"riscv_soc core write_back io_in_w_mem_en", false,-1);
        tracep->declQuad(c+121,"riscv_soc core write_back io_in_pc", false,-1, 63,0);
        tracep->declBus(c+123,"riscv_soc core write_back io_in_inst", false,-1, 31,0);
        tracep->declQuad(c+82,"riscv_soc core write_back io_in_mem_data", false,-1, 63,0);
        tracep->declBit(c+87,"riscv_soc core write_back io_in_mem_valid", false,-1);
        tracep->declBit(c+88,"riscv_soc core write_back io_in_w_ok", false,-1);
        tracep->declBus(c+114,"riscv_soc core write_back io_out_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+112,"riscv_soc core write_back io_out_result_data", false,-1, 63,0);
        tracep->declBit(c+115,"riscv_soc core write_back io_out_w_rs_en", false,-1);
        tracep->declQuad(c+5,"riscv_soc core write_back io_out_mem_wdata", false,-1, 63,0);
        tracep->declBit(c+9,"riscv_soc core write_back io_out_mem_wvalid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core write_back io_out_mem_addr", false,-1, 63,0);
        tracep->declBit(c+86,"riscv_soc core write_back io_out_mem_avalid", false,-1);
        tracep->declBus(c+10,"riscv_soc core write_back io_out_mem_wstrb", false,-1, 7,0);
        tracep->declBit(c+90,"riscv_soc core write_back io_out_stall", false,-1);
        tracep->declBit(c+11,"riscv_soc core write_back difftest_commit_0", false,-1);
        tracep->declQuad(c+12,"riscv_soc core write_back difftest_pc_0", false,-1, 63,0);
        tracep->declBus(c+14,"riscv_soc core write_back difftest_inst_0", false,-1, 31,0);
        tracep->declBit(c+90,"riscv_soc core write_back reg_stall", false,-1);
        tracep->declQuad(c+5,"riscv_soc core write_back reg_mem_wdata", false,-1, 63,0);
        tracep->declBus(c+10,"riscv_soc core write_back reg_mem_wstrb", false,-1, 7,0);
        tracep->declBit(c+9,"riscv_soc core write_back reg_mem_wvalid", false,-1);
        tracep->declQuad(c+3,"riscv_soc core write_back reg_mem_addr", false,-1, 63,0);
        tracep->declBus(c+263,"riscv_soc core write_back reg_rs_addr", false,-1, 4,0);
        tracep->declQuad(c+264,"riscv_soc core write_back reg_result_data", false,-1, 63,0);
        tracep->declBit(c+266,"riscv_soc core write_back reg_w_rs_en", false,-1);
        tracep->declQuad(c+267,"riscv_soc core write_back mem_data", false,-1, 63,0);
        tracep->declQuad(c+269,"riscv_soc core write_back mem_data_result", false,-1, 63,0);
        tracep->declQuad(c+271,"riscv_soc core write_back mem_wstrb", false,-1, 63,0);
        tracep->declBit(c+86,"riscv_soc core write_back reg_mem_avalid", false,-1);
        tracep->declBit(c+273,"riscv_soc core write_back reg_ls_state", false,-1);
        tracep->declBit(c+11,"riscv_soc core write_back difftest_commit", false,-1);
        tracep->declBus(c+274,"riscv_soc core write_back reg_inst", false,-1, 31,0);
        tracep->declQuad(c+275,"riscv_soc core write_back reg_pc", false,-1, 63,0);
        tracep->declBus(c+14,"riscv_soc core write_back difftest_inst", false,-1, 31,0);
        tracep->declQuad(c+12,"riscv_soc core write_back difftest_pc", false,-1, 63,0);
        tracep->declBus(c+277,"riscv_soc core write_back reg_exuType", false,-1, 5,0);
        tracep->declBit(c+278,"riscv_soc axi_ram clock", false,-1);
        tracep->declQuad(c+7,"riscv_soc axi_ram io_raddr", false,-1, 63,0);
        tracep->declQuad(c+1,"riscv_soc axi_ram io_rdata", false,-1, 63,0);
        tracep->declQuad(c+3,"riscv_soc axi_ram io_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc axi_ram io_wdata", false,-1, 63,0);
        tracep->declBus(c+10,"riscv_soc axi_ram io_wstrb", false,-1, 7,0);
        tracep->declBit(c+9,"riscv_soc axi_ram io_wen", false,-1);
        tracep->declBit(c+278,"riscv_soc axi_ram mem_clock", false,-1);
        tracep->declQuad(c+7,"riscv_soc axi_ram mem_raddr", false,-1, 63,0);
        tracep->declQuad(c+1,"riscv_soc axi_ram mem_rdata", false,-1, 63,0);
        tracep->declQuad(c+3,"riscv_soc axi_ram mem_waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc axi_ram mem_wdata", false,-1, 63,0);
        tracep->declBus(c+10,"riscv_soc axi_ram mem_wstrb", false,-1, 7,0);
        tracep->declBit(c+9,"riscv_soc axi_ram mem_wen", false,-1);
        tracep->declBit(c+278,"riscv_soc axi_ram mem clock", false,-1);
        tracep->declQuad(c+7,"riscv_soc axi_ram mem raddr", false,-1, 63,0);
        tracep->declQuad(c+1,"riscv_soc axi_ram mem rdata", false,-1, 63,0);
        tracep->declQuad(c+3,"riscv_soc axi_ram mem waddr", false,-1, 63,0);
        tracep->declQuad(c+5,"riscv_soc axi_ram mem wdata", false,-1, 63,0);
        tracep->declBus(c+10,"riscv_soc axi_ram mem wstrb", false,-1, 7,0);
        tracep->declBit(c+9,"riscv_soc axi_ram mem wen", false,-1);
    }
}

void Vriscv_soc___024root__traceFullTop0(void* voidSelf, VerilatedVcd* tracep) VL_ATTR_COLD;
void Vriscv_soc___024root__traceChgTop0(void* voidSelf, VerilatedVcd* tracep);
void Vriscv_soc___024root__traceCleanup(void* voidSelf, VerilatedVcd* /*unused*/);

void Vriscv_soc___024root__traceRegister(Vriscv_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vriscv_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    {
        tracep->addFullCb(&Vriscv_soc___024root__traceFullTop0, vlSelf);
        tracep->addChgCb(&Vriscv_soc___024root__traceChgTop0, vlSelf);
        tracep->addCleanupCb(&Vriscv_soc___024root__traceCleanup, vlSelf);
    }
}

void Vriscv_soc___024root__traceFullSub0(Vriscv_soc___024root* vlSelf, VerilatedVcd* tracep) VL_ATTR_COLD;

void Vriscv_soc___024root__traceFullTop0(void* voidSelf, VerilatedVcd* tracep) {
    Vriscv_soc___024root* const __restrict vlSelf = static_cast<Vriscv_soc___024root*>(voidSelf);
    Vriscv_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    {
        Vriscv_soc___024root__traceFullSub0((&vlSymsp->TOP), tracep);
    }
}

void Vriscv_soc___024root__traceFullSub0(Vriscv_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vriscv_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlWide<3>/*95:0*/ __Vtemp1332;
    VlWide<3>/*95:0*/ __Vtemp1333;
    VlWide<3>/*95:0*/ __Vtemp1334;
    VlWide<3>/*95:0*/ __Vtemp1336;
    VlWide<3>/*95:0*/ __Vtemp1337;
    VlWide<3>/*95:0*/ __Vtemp1339;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullQData(oldp+1,(vlSelf->riscv_soc__DOT__axi_ram__DOT__mem_rdata),64);
        tracep->fullQData(oldp+3,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_mem_addr),64);
        tracep->fullQData(oldp+5,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_mem_wdata),64);
        tracep->fullQData(oldp+7,(vlSelf->riscv_soc__DOT__core_io_out_raddr),64);
        tracep->fullBit(oldp+9,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_mem_wvalid));
        tracep->fullCData(oldp+10,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_mem_wstrb),8);
        tracep->fullBit(oldp+11,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__difftest_commit));
        tracep->fullQData(oldp+12,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__difftest_pc),64);
        tracep->fullIData(oldp+14,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__difftest_inst),32);
        tracep->fullQData(oldp+15,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [1U]),64);
        tracep->fullQData(oldp+17,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [2U]),64);
        tracep->fullQData(oldp+19,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [3U]),64);
        tracep->fullQData(oldp+21,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [4U]),64);
        tracep->fullQData(oldp+23,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [5U]),64);
        tracep->fullQData(oldp+25,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [6U]),64);
        tracep->fullQData(oldp+27,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [7U]),64);
        tracep->fullQData(oldp+29,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [8U]),64);
        tracep->fullQData(oldp+31,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [9U]),64);
        tracep->fullQData(oldp+33,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0xaU]),64);
        tracep->fullQData(oldp+35,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0xbU]),64);
        tracep->fullQData(oldp+37,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0xcU]),64);
        tracep->fullQData(oldp+39,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0xdU]),64);
        tracep->fullQData(oldp+41,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0xeU]),64);
        tracep->fullQData(oldp+43,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0xfU]),64);
        tracep->fullQData(oldp+45,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x10U]),64);
        tracep->fullQData(oldp+47,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x11U]),64);
        tracep->fullQData(oldp+49,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x12U]),64);
        tracep->fullQData(oldp+51,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x13U]),64);
        tracep->fullQData(oldp+53,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x14U]),64);
        tracep->fullQData(oldp+55,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x15U]),64);
        tracep->fullQData(oldp+57,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x16U]),64);
        tracep->fullQData(oldp+59,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x17U]),64);
        tracep->fullQData(oldp+61,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x18U]),64);
        tracep->fullQData(oldp+63,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x19U]),64);
        tracep->fullQData(oldp+65,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x1aU]),64);
        tracep->fullQData(oldp+67,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x1bU]),64);
        tracep->fullQData(oldp+69,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x1cU]),64);
        tracep->fullQData(oldp+71,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x1dU]),64);
        tracep->fullQData(oldp+73,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x1eU]),64);
        tracep->fullQData(oldp+75,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                   [0x1fU]),64);
        tracep->fullQData(oldp+77,((QData)((IData)(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__difftest_inst))),64);
        tracep->fullQData(oldp+79,(vlSelf->riscv_soc__DOT__core__DOT__fetch__DOT__regPC),64);
        tracep->fullBit(oldp+81,(vlSelf->riscv_soc__DOT__core__DOT__fetch_io_out_rvalid));
        tracep->fullQData(oldp+82,(vlSelf->riscv_soc__DOT__core__DOT__tem_reg_rdata),64);
        tracep->fullBit(oldp+84,(vlSelf->riscv_soc__DOT__core__DOT__tem_reg_is_read_inst));
        tracep->fullBit(oldp+85,((1U & (~ (IData)(vlSelf->riscv_soc__DOT__core__DOT__tem_reg_is_read_inst)))));
        tracep->fullBit(oldp+86,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_mem_avalid));
        tracep->fullBit(oldp+87,(vlSelf->riscv_soc__DOT__core__DOT__tem_reg_is_read_mem));
        tracep->fullBit(oldp+88,((1U & (~ (IData)(vlSelf->riscv_soc__DOT__core__DOT__tem_reg_is_read_mem)))));
        tracep->fullBit(oldp+89,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_stall));
        tracep->fullBit(oldp+90,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_stall));
        tracep->fullQData(oldp+91,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_next_pc),64);
        tracep->fullBit(oldp+93,(vlSelf->riscv_soc__DOT__core__DOT__execute_io_out_valid_next_pc));
        tracep->fullBit(oldp+94,(vlSelf->riscv_soc__DOT__core__DOT__execute_io_out_flush));
        tracep->fullQData(oldp+95,(vlSelf->riscv_soc__DOT__core__DOT__fetch__DOT__regTempPC),64);
        tracep->fullIData(oldp+97,(vlSelf->riscv_soc__DOT__core__DOT__fetch_io_out_inst),32);
        tracep->fullCData(oldp+98,(vlSelf->riscv_soc__DOT__core__DOT__decode_io_out_opType),3);
        tracep->fullCData(oldp+99,(vlSelf->riscv_soc__DOT__core__DOT__decode_io_out_exuType),6);
        tracep->fullCData(oldp+100,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_rs1_addr),5);
        tracep->fullQData(oldp+101,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_rs1_data),64);
        tracep->fullCData(oldp+103,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_rs2_addr),5);
        tracep->fullQData(oldp+104,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_rs2_data),64);
        tracep->fullQData(oldp+106,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_imm),64);
        tracep->fullQData(oldp+108,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_pc),64);
        tracep->fullIData(oldp+110,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_inst),32);
        tracep->fullCData(oldp+111,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_dest_rs_addr),5);
        tracep->fullQData(oldp+112,(vlSelf->riscv_soc__DOT__core__DOT__write_back_io_out_result_data),64);
        tracep->fullCData(oldp+114,(vlSelf->riscv_soc__DOT__core__DOT__write_back_io_out_rs_addr),5);
        tracep->fullBit(oldp+115,(vlSelf->riscv_soc__DOT__core__DOT__write_back_io_out_w_rs_en));
        tracep->fullCData(oldp+116,((0x1fU & (IData)(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_rs_addr))),5);
        tracep->fullQData(oldp+117,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_rs_data),64);
        tracep->fullBit(oldp+119,(vlSelf->riscv_soc__DOT__core__DOT__execute_io_out_w_rs_en));
        tracep->fullCData(oldp+120,(vlSelf->riscv_soc__DOT__core__DOT__execute_io_out_exuType),6);
        tracep->fullQData(oldp+121,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_pc),64);
        tracep->fullIData(oldp+123,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_inst),32);
        tracep->fullCData(oldp+124,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_rs2_addr),5);
        tracep->fullQData(oldp+125,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_rs2_data),64);
        tracep->fullQData(oldp+127,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_mem_addr),64);
        tracep->fullBit(oldp+129,(vlSelf->riscv_soc__DOT__core__DOT__execute_io_out_mem_avalid));
        tracep->fullBit(oldp+130,(vlSelf->riscv_soc__DOT__core__DOT__execute_io_out_w_mem_en));
        tracep->fullBit(oldp+131,(vlSelf->riscv_soc__DOT__core__DOT__is_read_mem));
        tracep->fullBit(oldp+132,(vlSelf->riscv_soc__DOT__core__DOT__is_read_inst));
        tracep->fullBit(oldp+133,(vlSelf->riscv_soc__DOT__core__DOT__fetch__DOT__stall));
        tracep->fullBit(oldp+134,(vlSelf->riscv_soc__DOT__core__DOT__fetch__DOT__pc_valid));
        tracep->fullIData(oldp+135,(vlSelf->riscv_soc__DOT__core__DOT__fetch__DOT__regInst),32);
        tracep->fullQData(oldp+136,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu_io_op_data1),64);
        tracep->fullQData(oldp+138,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu_io_op_data2),64);
        tracep->fullQData(oldp+140,((((QData)((IData)(
                                                      vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_data[1U])) 
                                      << 0x20U) | (QData)((IData)(
                                                                  vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_data[0U])))),64);
        tracep->fullQData(oldp+142,((((QData)((IData)(
                                                      vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_pc[1U])) 
                                      << 0x20U) | (QData)((IData)(
                                                                  vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_pc[0U])))),64);
        tracep->fullBit(oldp+144,((1U & vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_pc[2U])));
        tracep->fullBit(oldp+145,((1U & vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_data[2U])));
        tracep->fullBit(oldp+146,((1U & ((IData)(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__valid) 
                                         >> 1U))));
        tracep->fullQData(oldp+147,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___next_pc3_T_1),64);
        tracep->fullBit(oldp+149,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__lsu_exu_io_w_mem_en));
        tracep->fullQData(oldp+150,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_rs_addr),64);
        tracep->fullBit(oldp+152,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_flush));
        tracep->fullBit(oldp+153,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_w_rs_en));
        tracep->fullCData(oldp+154,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_exuType),6);
        tracep->fullBit(oldp+155,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_mem_avalid));
        tracep->fullBit(oldp+156,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__reg_w_mem_en));
        tracep->fullCData(oldp+157,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__valid),4);
        tracep->fullWData(oldp+158,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__temp_w_en_and_rs_data),65);
        tracep->fullBit(oldp+161,((1U & vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__temp_w_en_and_rs_data[2U])));
        tracep->fullQData(oldp+162,((((QData)((IData)(
                                                      vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__temp_w_en_and_rs_data[1U])) 
                                      << 0x20U) | (QData)((IData)(
                                                                  vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__temp_w_en_and_rs_data[0U])))),64);
        tracep->fullQData(oldp+164,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__rs2_data),64);
        __Vtemp1332[0U] = 1U;
        __Vtemp1332[1U] = 0U;
        __Vtemp1332[2U] = 0U;
        VL_ADD_W(3, __Vtemp1333, __Vtemp1332, vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___subresult_T_2);
        __Vtemp1334[0U] = __Vtemp1333[0U];
        __Vtemp1334[1U] = __Vtemp1333[1U];
        __Vtemp1334[2U] = (1U & __Vtemp1333[2U]);
        tracep->fullWData(oldp+166,(__Vtemp1334),65);
        __Vtemp1336[0U] = 1U;
        __Vtemp1336[1U] = 0U;
        __Vtemp1336[2U] = 0U;
        VL_ADD_W(3, __Vtemp1337, __Vtemp1336, vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___subresult_T_2);
        tracep->fullBit(oldp+169,((1U & (~ (1U & __Vtemp1337[2U])))));
        tracep->fullBit(oldp+170,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__s_rs1_l_rs2));
        tracep->fullQData(oldp+171,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__sllw_temp),63);
        tracep->fullIData(oldp+173,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__srlw_temp),32);
        tracep->fullIData(oldp+174,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__sraw_temp),32);
        tracep->fullWData(oldp+175,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_data),128);
        __Vtemp1339[0U] = (IData)((0xfffffffffffffffeULL 
                                   & vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___next_pc3_T_1));
        __Vtemp1339[1U] = (IData)(((0xfffffffffffffffeULL 
                                    & vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___next_pc3_T_1) 
                                   >> 0x20U));
        __Vtemp1339[2U] = 1U;
        tracep->fullWData(oldp+179,(__Vtemp1339),65);
        tracep->fullWData(oldp+182,(vlSelf->riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__temp_result_pc),65);
        tracep->fullQData(oldp+185,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[0]),64);
        tracep->fullQData(oldp+187,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[1]),64);
        tracep->fullQData(oldp+189,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[2]),64);
        tracep->fullQData(oldp+191,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[3]),64);
        tracep->fullQData(oldp+193,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[4]),64);
        tracep->fullQData(oldp+195,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[5]),64);
        tracep->fullQData(oldp+197,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[6]),64);
        tracep->fullQData(oldp+199,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[7]),64);
        tracep->fullQData(oldp+201,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[8]),64);
        tracep->fullQData(oldp+203,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[9]),64);
        tracep->fullQData(oldp+205,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[10]),64);
        tracep->fullQData(oldp+207,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[11]),64);
        tracep->fullQData(oldp+209,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[12]),64);
        tracep->fullQData(oldp+211,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[13]),64);
        tracep->fullQData(oldp+213,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[14]),64);
        tracep->fullQData(oldp+215,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[15]),64);
        tracep->fullQData(oldp+217,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[16]),64);
        tracep->fullQData(oldp+219,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[17]),64);
        tracep->fullQData(oldp+221,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[18]),64);
        tracep->fullQData(oldp+223,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[19]),64);
        tracep->fullQData(oldp+225,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[20]),64);
        tracep->fullQData(oldp+227,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[21]),64);
        tracep->fullQData(oldp+229,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[22]),64);
        tracep->fullQData(oldp+231,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[23]),64);
        tracep->fullQData(oldp+233,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[24]),64);
        tracep->fullQData(oldp+235,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[25]),64);
        tracep->fullQData(oldp+237,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[26]),64);
        tracep->fullQData(oldp+239,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[27]),64);
        tracep->fullQData(oldp+241,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[28]),64);
        tracep->fullQData(oldp+243,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[29]),64);
        tracep->fullQData(oldp+245,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[30]),64);
        tracep->fullQData(oldp+247,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile[31]),64);
        tracep->fullQData(oldp+249,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile
                                    [0U]),64);
        tracep->fullCData(oldp+251,((0x1fU & (vlSelf->riscv_soc__DOT__core__DOT__fetch_io_out_inst 
                                              >> 0xfU))),5);
        tracep->fullQData(oldp+252,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile_rs1_data_MPORT_data),64);
        tracep->fullCData(oldp+254,((0x1fU & (vlSelf->riscv_soc__DOT__core__DOT__fetch_io_out_inst 
                                              >> 0x14U))),5);
        tracep->fullQData(oldp+255,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__regfile_rs2_data_MPORT_data),64);
        tracep->fullCData(oldp+257,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_opType),3);
        tracep->fullCData(oldp+258,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__reg_exuType),6);
        tracep->fullCData(oldp+259,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__instType),4);
        tracep->fullCData(oldp+260,((0x1fU & (vlSelf->riscv_soc__DOT__core__DOT__fetch_io_out_inst 
                                              >> 7U))),5);
        tracep->fullSData(oldp+261,((vlSelf->riscv_soc__DOT__core__DOT__fetch_io_out_inst 
                                     >> 0x14U)),12);
        tracep->fullBit(oldp+262,(vlSelf->riscv_soc__DOT__core__DOT__decode__DOT__temp_stall));
        tracep->fullCData(oldp+263,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_rs_addr),5);
        tracep->fullQData(oldp+264,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_result_data),64);
        tracep->fullBit(oldp+266,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_w_rs_en));
        tracep->fullQData(oldp+267,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__mem_data),64);
        tracep->fullQData(oldp+269,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__mem_data_result),64);
        tracep->fullQData(oldp+271,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__mem_wstrb),64);
        tracep->fullBit(oldp+273,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_ls_state));
        tracep->fullIData(oldp+274,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_inst),32);
        tracep->fullQData(oldp+275,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_pc),64);
        tracep->fullCData(oldp+277,(vlSelf->riscv_soc__DOT__core__DOT__write_back__DOT__reg_exuType),6);
        tracep->fullBit(oldp+278,(vlSelf->clock));
        tracep->fullBit(oldp+279,(vlSelf->reset));
        tracep->fullQData(oldp+280,(vlSelf->io_difftest_reg_0),64);
        tracep->fullQData(oldp+282,(vlSelf->io_difftest_reg_1),64);
        tracep->fullQData(oldp+284,(vlSelf->io_difftest_reg_2),64);
        tracep->fullQData(oldp+286,(vlSelf->io_difftest_reg_3),64);
        tracep->fullQData(oldp+288,(vlSelf->io_difftest_reg_4),64);
        tracep->fullQData(oldp+290,(vlSelf->io_difftest_reg_5),64);
        tracep->fullQData(oldp+292,(vlSelf->io_difftest_reg_6),64);
        tracep->fullQData(oldp+294,(vlSelf->io_difftest_reg_7),64);
        tracep->fullQData(oldp+296,(vlSelf->io_difftest_reg_8),64);
        tracep->fullQData(oldp+298,(vlSelf->io_difftest_reg_9),64);
        tracep->fullQData(oldp+300,(vlSelf->io_difftest_reg_10),64);
        tracep->fullQData(oldp+302,(vlSelf->io_difftest_reg_11),64);
        tracep->fullQData(oldp+304,(vlSelf->io_difftest_reg_12),64);
        tracep->fullQData(oldp+306,(vlSelf->io_difftest_reg_13),64);
        tracep->fullQData(oldp+308,(vlSelf->io_difftest_reg_14),64);
        tracep->fullQData(oldp+310,(vlSelf->io_difftest_reg_15),64);
        tracep->fullQData(oldp+312,(vlSelf->io_difftest_reg_16),64);
        tracep->fullQData(oldp+314,(vlSelf->io_difftest_reg_17),64);
        tracep->fullQData(oldp+316,(vlSelf->io_difftest_reg_18),64);
        tracep->fullQData(oldp+318,(vlSelf->io_difftest_reg_19),64);
        tracep->fullQData(oldp+320,(vlSelf->io_difftest_reg_20),64);
        tracep->fullQData(oldp+322,(vlSelf->io_difftest_reg_21),64);
        tracep->fullQData(oldp+324,(vlSelf->io_difftest_reg_22),64);
        tracep->fullQData(oldp+326,(vlSelf->io_difftest_reg_23),64);
        tracep->fullQData(oldp+328,(vlSelf->io_difftest_reg_24),64);
        tracep->fullQData(oldp+330,(vlSelf->io_difftest_reg_25),64);
        tracep->fullQData(oldp+332,(vlSelf->io_difftest_reg_26),64);
        tracep->fullQData(oldp+334,(vlSelf->io_difftest_reg_27),64);
        tracep->fullQData(oldp+336,(vlSelf->io_difftest_reg_28),64);
        tracep->fullQData(oldp+338,(vlSelf->io_difftest_reg_29),64);
        tracep->fullQData(oldp+340,(vlSelf->io_difftest_reg_30),64);
        tracep->fullQData(oldp+342,(vlSelf->io_difftest_reg_31),64);
        tracep->fullQData(oldp+344,(vlSelf->io_difftest_pc),64);
        tracep->fullIData(oldp+346,(vlSelf->io_difftest_inst),32);
        tracep->fullBit(oldp+347,(vlSelf->io_difftest_commit));
        tracep->fullQData(oldp+348,(0ULL),64);
        tracep->fullBit(oldp+350,(0U));
        tracep->fullCData(oldp+351,(0U),8);
        tracep->fullBit(oldp+352,(1U));
        tracep->fullCData(oldp+353,(0U),5);
        tracep->fullCData(oldp+354,(1U),5);
        tracep->fullCData(oldp+355,(2U),5);
        tracep->fullCData(oldp+356,(3U),5);
        tracep->fullCData(oldp+357,(4U),5);
        tracep->fullCData(oldp+358,(5U),5);
        tracep->fullCData(oldp+359,(6U),5);
        tracep->fullCData(oldp+360,(7U),5);
        tracep->fullCData(oldp+361,(8U),5);
        tracep->fullCData(oldp+362,(9U),5);
        tracep->fullCData(oldp+363,(0xaU),5);
        tracep->fullCData(oldp+364,(0xbU),5);
        tracep->fullCData(oldp+365,(0xcU),5);
        tracep->fullCData(oldp+366,(0xdU),5);
        tracep->fullCData(oldp+367,(0xeU),5);
        tracep->fullCData(oldp+368,(0xfU),5);
        tracep->fullCData(oldp+369,(0x10U),5);
        tracep->fullCData(oldp+370,(0x11U),5);
        tracep->fullCData(oldp+371,(0x12U),5);
        tracep->fullCData(oldp+372,(0x13U),5);
        tracep->fullCData(oldp+373,(0x14U),5);
        tracep->fullCData(oldp+374,(0x15U),5);
        tracep->fullCData(oldp+375,(0x16U),5);
        tracep->fullCData(oldp+376,(0x17U),5);
        tracep->fullCData(oldp+377,(0x18U),5);
        tracep->fullCData(oldp+378,(0x19U),5);
        tracep->fullCData(oldp+379,(0x1aU),5);
        tracep->fullCData(oldp+380,(0x1bU),5);
        tracep->fullCData(oldp+381,(0x1cU),5);
        tracep->fullCData(oldp+382,(0x1dU),5);
        tracep->fullCData(oldp+383,(0x1eU),5);
        tracep->fullCData(oldp+384,(0x1fU),5);
    }
}
