// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vriscv_soc.h for the primary calling header

#ifndef VERILATED_VRISCV_SOC___024ROOT_H_
#define VERILATED_VRISCV_SOC___024ROOT_H_  // guard

#include "verilated_heavy.h"

//==========

class Vriscv_soc__Syms;
class Vriscv_soc___024unit;


//----------

VL_MODULE(Vriscv_soc___024root) {
  public:
    // CELLS
    Vriscv_soc___024unit* __PVT____024unit;

    // PORTS
    VL_IN8(clock,0,0);
    VL_IN8(reset,0,0);
    VL_OUT8(io_difftest_commit,0,0);
    VL_OUT8(io_difftest_irq,0,0);
    VL_OUT8(io_difftest_peripheral,0,0);
    VL_OUT(io_difftest_inst,31,0);
    VL_OUT64(io_difftest_reg_0,63,0);
    VL_OUT64(io_difftest_reg_1,63,0);
    VL_OUT64(io_difftest_reg_2,63,0);
    VL_OUT64(io_difftest_reg_3,63,0);
    VL_OUT64(io_difftest_reg_4,63,0);
    VL_OUT64(io_difftest_reg_5,63,0);
    VL_OUT64(io_difftest_reg_6,63,0);
    VL_OUT64(io_difftest_reg_7,63,0);
    VL_OUT64(io_difftest_reg_8,63,0);
    VL_OUT64(io_difftest_reg_9,63,0);
    VL_OUT64(io_difftest_reg_10,63,0);
    VL_OUT64(io_difftest_reg_11,63,0);
    VL_OUT64(io_difftest_reg_12,63,0);
    VL_OUT64(io_difftest_reg_13,63,0);
    VL_OUT64(io_difftest_reg_14,63,0);
    VL_OUT64(io_difftest_reg_15,63,0);
    VL_OUT64(io_difftest_reg_16,63,0);
    VL_OUT64(io_difftest_reg_17,63,0);
    VL_OUT64(io_difftest_reg_18,63,0);
    VL_OUT64(io_difftest_reg_19,63,0);
    VL_OUT64(io_difftest_reg_20,63,0);
    VL_OUT64(io_difftest_reg_21,63,0);
    VL_OUT64(io_difftest_reg_22,63,0);
    VL_OUT64(io_difftest_reg_23,63,0);
    VL_OUT64(io_difftest_reg_24,63,0);
    VL_OUT64(io_difftest_reg_25,63,0);
    VL_OUT64(io_difftest_reg_26,63,0);
    VL_OUT64(io_difftest_reg_27,63,0);
    VL_OUT64(io_difftest_reg_28,63,0);
    VL_OUT64(io_difftest_reg_29,63,0);
    VL_OUT64(io_difftest_reg_30,63,0);
    VL_OUT64(io_difftest_reg_31,63,0);
    VL_OUT64(io_difftest_pc,63,0);
    VL_OUT64(io_inst_counter,63,0);
    VL_OUT64(io_difftest_mstatus,63,0);
    VL_OUT64(io_difftest_mcause,63,0);
    VL_OUT64(io_difftest_mepc,63,0);
    VL_OUT64(io_difftest_mtvec,63,0);

    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ riscv_soc__DOT___axi_ram_io_ram_bus_r_bits_rlast;
        CData/*0:0*/ riscv_soc__DOT___core_io_axi_bus_w_valid;
        CData/*7:0*/ riscv_soc__DOT___core_io_axi_bus_w_bits_wstrb;
        CData/*0:0*/ riscv_soc__DOT___core_io_axi_bus_w_bits_wlast;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___execute_io_csr_except_is_except;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___execute_io_csr_except_is_time_irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___execute_io_csr_except_is_soft_irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___execute_io_commit;
        CData/*7:0*/ riscv_soc__DOT__core__DOT___execute_io_bus_bits_wstrb;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___execute_io_bus_bits_is_w;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_fetch_cpu_addr_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_fetch_cpu_data_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_DCache_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_bus1_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_bus2_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_clint_bus_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_io_ICache_bus_r_bits_rlast;
        CData/*0:0*/ riscv_soc__DOT__core__DOT___cross_bar_io_DCache_bus_r_bits_rlast;
        CData/*5:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT___cache_stage1_io_tag_valid_index;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT___cache_stage1_io_cache_stage1_bits_sram_0_hit;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT___cache_stage1_io_cache_stage1_bits_sram_1_hit;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__is_w_sram;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__is_sram0_write;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__is_sram1_write;
        CData/*5:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__sram_addr;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__reg_temp_sram0_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__reg_temp_sram1_valid;
        CData/*5:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__reg_temp_r_index;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__w_r_pass0_val;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__w_r_pass1_val;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__reg_sram_r_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage0__DOT__reg_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage1__DOT__valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage1__DOT__ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage1__DOT__reg_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_chosen_tag;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_r_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_cache_write;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_bus_state;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT__valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___T_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___T_4;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___T_7;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___GEN_0;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___T_9;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___T_10;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___GEN_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_2;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_cache_state;
        CData/*7:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_wstrb;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_is_w;
        CData/*5:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_index;
        CData/*3:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_offset;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_cache_write;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_chosen_tag;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__is_sram0_write;
        CData/*5:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__sram0_A;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__is_sram2_write;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_r_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_w_wlast;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_w_valid;
    };
    struct {
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_b_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_start_operation;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_cnt;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_rbus_finish;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_wbus_finish;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__hit_0;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__hit_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_6;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___GEN_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_7;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_11;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___GEN_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___GEN_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_12;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_13;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_14;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_15;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_19;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___T_21;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___GEN_4;
        CData/*7:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___GEN_5;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_6;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk4__DOT___GEN_7;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk4__DOT___T_16;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__w_locked;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__w_lockId;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___GEN;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__reg_r_cnt;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__r_lockId;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___T_7;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___GEN_0;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___io_ICache_bus_r_ready_T_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___io_DCache_bus_r_ready_T_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___io_bus1_ready_T_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___io_bus2_ready_T_4;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__reg_aw_ok;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___io_AXI_Bus_aw_valid_T_9;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__reg_ar_ok;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT___GEN_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__unnamedblk1__DOT___T_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar__DOT__unnamedblk2__DOT___T_9;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__cross_bar_1__DOT__not_clint;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__reg_flush;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__reg_bus_valid;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__pre_info_head;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__pre_info_tail;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__is_pre_head;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__is_pre_tail;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__is_pre_fifo_0;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__is_pre_fifo_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__is_pre_fifo_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__is_pre_fifo_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT___io_out_flush_T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__unnamedblk1__DOT___T_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__unnamedblk1__DOT__unnamedblk2__DOT__pre_enq;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__reg_head;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__reg_tail;
        CData/*2:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__reg_ibuf_size;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__enq_size;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__can_deq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT___GEN;
    };
    struct {
        CData/*1:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT___PHT_ext_R1_data;
        CData/*2:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT__reg_head;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT__pre_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___io_flush_T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___io_csr_valid_T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___io_wb_valid_T_2;
        CData/*4:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_dest_addr;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___system_exu_io_is_except;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___system_exu_io_valid_next_pc;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__in_data_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__ready;
        CData/*3:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_valid;
        CData/*3:0*/ riscv_soc__DOT__core__DOT__execute__DOT___GEN;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___alu_exu_io_valid_T_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT___system_exu_io_valid_T_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_sys_alu_w_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_br_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_br_mispredict;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_taken;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_csr_is_w;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_is_except;
        CData/*5:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_exception;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_is_time_irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_is_soft_irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_valid_next_pc;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_fence_i;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_commit;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__unnamedblk1__DOT___T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__unnamedblk1__DOT__time_irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__unnamedblk1__DOT__soft_irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__unnamedblk1__DOT___reg_valid_next_pc_T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__is_pre;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__br_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___io_br_info_mispredict_T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_ready;
        CData/*7:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_bus_wstrb;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_bus_is_w;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_bus_valid;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_w_rs_en;
        CData/*6:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_exuType;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__w_mem_en;
        CData/*7:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT___GEN;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_ls_state;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT___io_bus_valid_T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__unnamedblk1__DOT___T_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__unnamedblk1__DOT___GEN_0;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_1;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_state;
        CData/*6:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_cnt;
        CData/*6:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_exuType;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_dest_is_w;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___T_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___T_6;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN_0;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN_1;
        CData/*7:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN_4;
        IData/*27:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN_5;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_ready;
        CData/*1:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_state;
        CData/*6:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_exuType;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_dest_is_w;
        CData/*6:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_cnt;
    };
    struct {
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___T;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___T_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___GEN_1;
        CData/*7:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___GEN_2;
        IData/*27:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___GEN_4;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__system_exu__DOT__is_ret;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_valid;
        CData/*2:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_opType;
        CData/*6:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_exuType;
        CData/*4:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_rs1_addr;
        CData/*4:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_rs2_addr;
        CData/*4:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_dest_addr;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_dest_is_reg;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_is_pre;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_1;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_5;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_7;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_9;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_11;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_13;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_15;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_17;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_19;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_21;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_23;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_25;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_27;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_29;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_31;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_33;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_35;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_37;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_39;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_41;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_43;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_45;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_47;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_49;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_51;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_53;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_55;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_57;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_59;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_61;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_63;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_65;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_67;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_69;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_71;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_73;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_75;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_77;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_79;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_81;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_83;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_85;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_87;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_89;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_91;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_93;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_95;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_97;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_99;
    };
    struct {
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_101;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_103;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_105;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_107;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_109;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_111;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_113;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_115;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_117;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_119;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_121;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_123;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_125;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_127;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_129;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_131;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_133;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_135;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_137;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_139;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_141;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_143;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_145;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_147;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___T_149;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_3;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_4;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_5;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_6;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_7;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_8;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_9;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_10;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_11;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_12;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_13;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_14;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_15;
        CData/*3:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT__instType;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_16;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_18;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_20;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_22;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__unnamedblk1__DOT__irq;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__unnamedblk1__DOT___T_2;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__reg_msip;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__reg_ready;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__reg_state;
        CData/*0:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__unnamedblk1__DOT___GEN;
        CData/*3:0*/ riscv_soc__DOT__axi_ram__DOT__reg_rlen;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_ar_ready;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_r_valid;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_r_state;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT___T_4;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_is_w;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_aw_ready;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_w_ready;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__reg_b_valid;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__unnamedblk1__DOT___T_5;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__unnamedblk1__DOT___T_6;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__unnamedblk1__DOT___GEN;
        CData/*0:0*/ riscv_soc__DOT__axi_ram__DOT__unnamedblk1__DOT__unnamedblk2__DOT___T_1;
        SData/*15:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_cache_wstrb;
    };
    struct {
        SData/*11:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_csr_addr;
        SData/*11:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_csr_addr;
        SData/*9:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_0;
        SData/*15:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN_1;
        IData/*31:0*/ riscv_soc__DOT__core__DOT___fetch_io_put_pc_bits_inst;
        VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_cache_wdata;
        VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_cache_wdata;
        VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__cache_mask;
        VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__unnamedblk2__DOT___cache_wdata_T_1;
        VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__unnamedblk2__DOT___cache_wdata_T_2;
        VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT___BTB_ext_R0_data;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___GEN_4;
        VlWide<4>/*126:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__mem_w_data;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_divisor;
        VlWide<3>/*65:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_dividend;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_rem;
        VlWide<3>/*65:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__reg_q;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT__dividend;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___divisor_T_8;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___divisor_T_14;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT__divisor;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT__rem;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT__neg_divisor;
        VlWide<5>/*130:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN;
        VlWide<3>/*65:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___reg_q_T;
        VlWide<9>/*259:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN_2;
        VlWide<9>/*263:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__div__DOT__unnamedblk1__DOT___GEN_3;
        VlWide<3>/*66:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_temp_mul2;
        VlWide<5>/*129:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_mul1;
        VlWide<5>/*129:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__reg_result;
        VlWide<5>/*129:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___pp_T_9;
        VlWide<33>/*1039:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___GEN;
        VlWide<5>/*129:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___GEN_0;
        VlWide<17>/*519:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT___GEN_3;
        VlWide<3>/*64:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT__mul__DOT__unnamedblk1__DOT__unnamedblk2__DOT__mul_data2;
        IData/*31:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_imm;
        IData/*16:0*/ riscv_soc__DOT__core__DOT__decode__DOT__unnamedblk1__DOT___GEN;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram0__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram1__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram2__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram3__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram4__DOT___sram_ext_R0_data;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram4__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram5__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram6__DOT___sram_ext_R0_data;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram6__DOT__Q;
        VlWide<4>/*127:0*/ riscv_soc__DOT__sram7__DOT__Q;
        QData/*63:0*/ riscv_soc__DOT___axi_ram_io_ram_bus_r_bits_rdata;
        QData/*63:0*/ riscv_soc__DOT___core_io_axi_bus_ar_bits_araddr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___commit_io_csr_rd_csr_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___commit_io_csr_pass_csr_mepc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___commit_io_csr_pass_csr_mstatus;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___commit_io_csr_pass_csr_mie;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___execute_io_bus_bits_addr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___execute_io_bus_bits_wdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_fetch_cpu_data_bits_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_fetch_cpu_data_bits_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT___cross_bar_1_io_wb_bits_rdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__reg_sram0_valid;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__reg_sram1_valid;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__unnamedblk1__DOT___GEN;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__unnamedblk1__DOT___reg_temp_sram0_valid_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__unnamedblk1__DOT___reg_temp_sram1_valid_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__unnamedblk1__DOT__unnamedblk2__DOT__chose_bit;
    };
    struct {
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage0__DOT__reg_addr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage1__DOT__reg_cpu_addr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_rdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_r_raddr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_cpu_addr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__reg_lru_1;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___GEN;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT___LRU_1_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT__cache_stage2__DOT__unnamedblk1__DOT__unnamedblk3__DOT__chose_bit;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_wdata;
        QData/*53:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_tag;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_rdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_sram0_valid;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_sram0_dirty;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_sram2_valid;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_sram2_dirty;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_r_raddr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_w_waddr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_w_wdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__reg_lru_2;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___GEN_0;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__chose_bit;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___tag_valid_0_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___tag_valid_2_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___LRU_2_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___tag_dirty_2_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT___tag_dirty_0_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__d_cache__DOT__unnamedblk1__DOT__unnamedblk5__DOT___GEN_8;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT___br_predictor_io_pre_next_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__reg_pc_0;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__reg_next_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__pre_info_fifo_0;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__pre_info_fifo_1;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__pre_info_fifo_2;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__pre_info_fifo_3;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT___io_wb_dest_data_T_3;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_csr_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__rs1_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__rs2_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_sys_alu_wdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_br_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_br_next_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_except_next_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_except_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__reg_next_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT__dst_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__alu_exu__DOT___io_br_info_target_next_pc_T;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_bus_addr;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_bus_wdata;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__reg_result_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__mem_addr;
        VlWide<16>/*511:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_2;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mem_exu__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__mem_r_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__system_exu__DOT__op_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__system_exu__DOT__or_result;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT__system_exu__DOT__and_result;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_rs1_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_rs2_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_pc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__decode__DOT__reg_csr_data;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_0;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_1;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_2;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_3;
    };
    struct {
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_4;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_5;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_6;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_7;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_8;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_9;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_10;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_11;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_12;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_13;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_14;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_15;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_16;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_17;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_18;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_19;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_20;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_21;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_22;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_23;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_24;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_25;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_26;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_27;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_28;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_29;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_30;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__reg_file_31;
        VlWide<64>/*2047:0*/ riscv_soc__DOT__core__DOT__commit__DOT___GEN;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mstatus;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mie;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mtvec;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mscratch;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mepc;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mcause;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mtval;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_mcycle;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__commit__DOT__csr_reg__DOT__reg_minstret;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__reg_mtime;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__reg_mtimecmp;
        QData/*63:0*/ riscv_soc__DOT__core__DOT__clint_de__DOT__red_rdata;
        QData/*63:0*/ riscv_soc__DOT__axi_ram__DOT__reg_raddr;
        QData/*63:0*/ riscv_soc__DOT__axi_ram__DOT__reg_w_addr;
        VlUnpacked<QData/*63:0*/, 4> riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__ibuf_pc_ext__DOT__Memory;
        VlUnpacked<IData/*31:0*/, 4> riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__ibuf_inst_ext__DOT__Memory;
        VlUnpacked<CData/*0:0*/, 4> riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__ibuf_is_pre_ext__DOT__Memory;
        VlUnpacked<CData/*0:0*/, 4> riscv_soc__DOT__core__DOT__fetch__DOT__ibuf__DOT__ibuf_valid_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT__BTB_ext__DOT__Memory;
        VlUnpacked<QData/*63:0*/, 6> riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT__RAS_ext__DOT__Memory;
        VlUnpacked<CData/*1:0*/, 64> riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT__PHT_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram0__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram1__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram2__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram3__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram4__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram5__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram6__DOT__sram_ext__DOT__Memory;
        VlUnpacked<VlWide<4>/*127:0*/, 64> riscv_soc__DOT__sram7__DOT__sram_ext__DOT__Memory;
    };

    // LOCAL VARIABLES
    CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT____Vcellinp__mem_exu__io_valid;
    CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT____Vcellinp__div__io_valid;
    CData/*0:0*/ riscv_soc__DOT__core__DOT__execute__DOT__mu_exu__DOT____Vcellinp__mul__io_valid;
    CData/*0:0*/ __Vclklast__TOP__clock;
    VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT____Vcellinp__cache_stage1__io_sram_sram_data_1;
    VlWide<4>/*127:0*/ riscv_soc__DOT__core__DOT__i_cache__DOT____Vcellinp__cache_stage1__io_sram_sram_data_0;
    QData/*63:0*/ riscv_soc__DOT__core__DOT__fetch__DOT__br_predictor__DOT__RAS_ext__DOT____Vlvbound1;
    QData/*63:0*/ riscv_soc__DOT__core__DOT__execute__DOT____Vcellinp__system_exu__io_csr_data;

    // INTERNAL VARIABLES
    Vriscv_soc__Syms* vlSymsp;  // Symbol table

    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vriscv_soc___024root);  ///< Copying not allowed
  public:
    Vriscv_soc___024root(const char* name);
    ~Vriscv_soc___024root();

    // INTERNAL METHODS
    void __Vconfigure(Vriscv_soc__Syms* symsp, bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
